### ISSUE TITLE
Package libwxgtk3.0-dev is not available.

### ISSUE THREAD

**Issue by TheFlashDrive** [grandaspanna/Non-planar-Slic3r-in-WSL-for-Windows-10#3]
I just spent the last minute or so typing in the `sudo apt-get install gcc cmake build-essential libgtk2.0-dev libwxgtk3.0-dev libwx-perl libmodule-build-perl git cpanminus libextutils-cppguess-perl libboost-all-dev libxmu-dev liblocal-lib-perl wx-common libopengl-perl libwx-glcanvas-perl libtbb-dev libxmu-dev freeglut3-dev libwxgtk-media3.0-dev libboost-thread-dev libboost-system-dev libboost-filesystem-dev libcurl4-openssl-dev libextutils-makemaker-cpanfile-perl` command and then I was given the error message "Package libwxgtk3.0-dev is not available, but is referred to by another package" and "Unable to locate package 'libwxgtk-media3.0-dev'". Can someone help me fix this? By the way, I'm using Ubuntu version 20.04 LTS.

**Comment by grandaspanna** [comment]
It's usually easier to cut-and-paste the commands 👍 

Now, to the core of the issue, I think there was a change in the packaging for 20.04, which I haven't been able to test personally. However, the suggested fix is to change libwxgtk3.0-dev to libgtk3.0-gtk3-dev

Let me know how that goes.

**Comment by TheFlashDrive** [comment]
Sorry for a late response, I've been busy with school. 
I'm not entirely sure why, but I'm unable to paste anything into terminal from windows, but I can copy things from terminal and paste it into windows.

Anyway, I have now multiple different error messages:

E: Unable to locate package libgtk3.0-gtk3-dev
E: Couldn't find any package by glob 'libgtk3.0-gtk3-dev'
E: Couldn't find any package by regex 'libgtk3.0-gtk3-dev'
E: Unable to locate package libwxgtk-media3.0-dev
E: Couldn't find any package by glob 'libwxgtk-media3.0-dev'
E: Couldn't find any package by regex 'libwxgtk-media3.0-dev'
E: Unable to locate package libcurl14-openssl-dev

Do you think rolling back to Ubuntu version 18.04 LTS could fix the issue (I'm new to Linux, and I'm still figuring a few things out). Thanks for helping me with this.

**Comment by grandaspanna** [comment]
I've just installed a 20.04 instance on my PC to try out. My previous reply was done in the absence of trying it, but now that I've started there are two corrections to that command:
1) The aforementioned libwxgtk3.0-dev should, in fact, be libwxgtk3.0-gtk3-dev
2)  libwxgtk-media3.0-dev should be replaced with libwxgtk-media3.0-gtk3-dev

That will get that set of components installing. It's still in progress on my computer, but don't know if I'll have time to get back to it this evening.

Note that "apt search <string>' can be used at a command prompt to search for package names. Linux can be a lot of fun, even if the lines between operating systems is getting increasingly blurred.

**Comment by grandaspanna** [comment]
I may have made things more difficult for myself by upgrading to WSL2, but I know it can be made to work :-)

The build completes and now runs with 20.04, but the WSL2 changes to networking make the setup just a fraction more complicated.

Hopefully I can add some updates in the next few days, but the basic issues are:
* WSL2 runs the Linux instance at a different network address
* Because of this, the Windows firewall steps in, blocking port 6000
* The DISPLAY variable needs to point to the IP address of the WIndows network interface (localhost no longer works)
* Need to setup access control on the Xserver to allow a "remote" app to connect

None of these things are particularly difficult, but need to be addressed.
